In [ ]:
import pandas as pd
from functools import reduce

data = pd.read_json("dados_video_game.json")

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon RedPokemon Blue,GB,1996,Role Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [31]:
data.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Alta_Venda,Vendas_Unidades,Vendas_Formatadas
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,True,82740000,82.740.000
1,2,Super Mario Bros,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,True,40240000,40.240.000
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,True,35820000,35.820.000
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,True,33000000,33.000.000
4,5,Pokemon RedPokemon Blue,GB,1996,Role Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,True,31370000,31.370.000

In [25]:
data.loc[(data["Year"] > 2010) & (data["Year"] < 2015) & (data["Platform"] == "PSThree")]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Alta_Venda
16,17,Grand Theft Auto V,PSThree,2013,Action,TakeTwo Interactive,7.01,9.27,0.97,4.14,21.40,True
33,35,Call of Duty Black Ops II,PSThree,2012,Shooter,Activision,4.99,5.88,0.65,2.52,14.03,False
73,83,FIFA Soccer OneThree,PSThree,2012,Action,Electronic Arts,1.06,5.05,0.13,2.01,8.24,False
101,113,FIFA OneFour,PSThree,2013,Sports,Electronic Arts,0.78,4.32,0.07,1.73,6.90,False
104,116,Uncharted Three Drakes Deception,PSThree,2011,Action,Sony Computer Entertainment,2.77,2.80,0.19,1.06,6.83,False
...,...,...,...,...,...,...,...,...,...,...,...,...
11199,16218,Tsukigime Rankos Longest Day,PSThree,2014,Action,Namco Bandai Games,0.00,0.01,0.00,0.00,0.01,False
11223,16253,Strider TwoZeroOneFour,PSThree,2014,Platform,Capcom,0.00,0.00,0.01,0.00,0.01,False
11335,16413,Sakigake Otokojuku Nihon yo Kore ga Otoko Dearu,PSThree,2014,Fighting,Namco Bandai Games,0.00,0.00,0.01,0.00,0.01,False
11366,16454,Shin Koihime Musou Otome Taisen Sangokushi Engi,PSThree,2014,Adventure,Views,0.00,0.00,0.01,0.00,0.01,False
11385,16483,MuvLuv Alternative,PSThree,2012,Simulation,Fivepb,0.00,0.00,0.01,0.00,0.01,False

In [ ]:
data["Global_Sales"] = data["Global_Sales"].astype(float)

data["Altíssima_Venda"] = data["Global_Sales"].apply(lambda valor: valor > 20)
data["Alta_Venda"] = data["Global_Sales"].apply(lambda valor: valor > 10)
data["Boa_Venda"] = data["Global_Sales"].apply(lambda valor: valor > 1)
data["Média_Venda"] = data["Global_Sales"].apply(lambda valor: valor < 1)
data["Baixa_Venda"] = data["Global_Sales"].apply(lambda valor: valor < 0.1)
data["Vendas_Unidades"] = data["Global_Sales"].astype(float).apply(lambda x: int(x * 1_000_000))
data["Vendas_Formatadas"] = data["Vendas_Unidades"].apply(lambda x: f"{x:,}".replace(",", "."))

print(data[["Name", "Global_Sales", "Alta_Venda"]].head())

                      Name  Global_Sales  Alta_Venda
0               Wii Sports         82.74        True
1         Super Mario Bros         40.24        True
2           Mario Kart Wii         35.82        True
3        Wii Sports Resort         33.00        True
4  Pokemon RedPokemon Blue         31.37        True

In [45]:
data.loc[(data["Global_Sales"] < 0.1) & (data["Platform"] == "PSThree")]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Alta_Venda,Vendas_Unidades,Vendas_Formatadas,Altíssima_Venda,Boa_Venda,Pouca_Venda,Média_Venda,Baixa_Venda
7380,10843,SingStar ApresSki Party Two,PSThree,2010,Misc,Sony Computer Entertainment,0.00,0.07,0.00,0.02,0.09,False,90000,90.000,False,False,True,True,False
7451,10941,WSC Real OneOne World Snooker Championship,PSThree,2011,Sports,Koch Media,0.00,0.07,0.00,0.02,0.09,False,90000,90.000,False,False,True,True,False
7460,10959,Resident Evil Chronicles HD,PSThree,2012,Shooter,Capcom,0.00,0.00,0.09,0.00,0.09,False,90000,90.000,False,False,True,True,False
7468,10969,SingStar Made In Germany,PSThree,2009,Misc,Sony Computer Entertainment,0.00,0.07,0.00,0.02,0.09,False,90000,90.000,False,False,True,True,False
7476,10979,Young Justice Legacy,PSThree,2013,Action,Namco Bandai Games,0.06,0.02,0.00,0.01,0.09,False,90000,90.000,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11309,16369,Hakuouki Shinsengumi Kitan,PSThree,0,Adventure,Unknown,0.01,0.00,0.00,0.00,0.01,False,10000,10.000,False,False,True,True,False
11335,16413,Sakigake Otokojuku Nihon yo Kore ga Otoko Dearu,PSThree,2014,Fighting,Namco Bandai Games,0.00,0.00,0.01,0.00,0.01,False,10000,10.000,False,False,True,True,False
11344,16425,Railfan,PSThree,2006,Simulation,Ongakukan,0.00,0.00,0.01,0.00,0.01,False,10000,10.000,False,False,True,True,False
11366,16454,Shin Koihime Musou Otome Taisen Sangokushi Engi,PSThree,2014,Adventure,Views,0.00,0.00,0.01,0.00,0.01,False,10000,10.000,False,False,True,True,False
11385,16483,MuvLuv Alternative,PSThree,2012,Simulation,Fivepb,0.00,0.00,0.01,0.00,0.01,False,10000,10.000,False,False,True,True,False

In [47]:
# 1. Sum - Soma os dados de uma coluna
total_na_sales = data['NA_Sales'].sum()
print(f"Soma das vendas na América do Norte: {total_na_sales}")

Soma das vendas na América do Norte: 3274.55

In [ ]:
# 2. Filter - Filtra valores maiores que 10 em 'NA_Sales'
maior_que_10 = data['NA_Sales'].apply(lambda x: x > 10)
num_filtrados = data[maior_que_10]
print(f"Jogos com vendas maiores que 10 milhões na América do Norte:\n{num_filtrados}")

In [ ]:
# 3. Map - Multiplicar cada valor em 'Global_Sales' por 3
data['Global_Sales_triplicado'] = data['Global_Sales'].map(lambda x: x * 3)
print(f"DataFrame com 'Global_Sales' triplicados:\n{data}")

In [ ]:
# 4. Reduce - Somar todas as vendas globais
total_global_sales = reduce(lambda x, y: x + y, data['Global_Sales'])
print(f"Soma total de 'Global_Sales' usando reduce: {total_global_sales}")